# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20170808_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
