# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
