# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20170808_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_confir',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
