# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(blank=True),
        ),
    ]
